version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRESDATABASE_HOST: ${POSTGRES_HOST}
      POSTGRES DATABASE_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: